#!/usr/bin/env bash
# cv3_margins — score effect or ranking artifact?
#
# GENERATED by tools/emit_exp_modules.py from results/cv3_margins_410m.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="cv3_margins"; MODULE_TITLE="score effect or ranking artifact?"
MODULE_WHY="score effect or ranking artifact?"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=(results/e48/lens_INSTREAM_Github_410m_n200_s0.pt results/e48/lens_INSTREAM_Github_410m_n200_s1.pt results/e48/lens_INSTREAM_Github_410m_n200_s2.pt results/e48/lens_INSTREAM_Pile-CC_410m_n200_s0.pt results/e48/lens_INSTREAM_Pile-CC_410m_n200_s1.pt results/e48/lens_INSTREAM_Pile-CC_410m_n200_s2.pt)
OUTPUTS=(results/cv3_margins_410m.json)
main() { run_py experiments/cv3_margins.py; }
module_main "$@"
