#!/usr/bin/env bash
# cv4_capability — answer competence across the ladder
#
# GENERATED by tools/emit_exp_modules.py from results/cv4_phase1_capability.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="cv4_capability"; MODULE_TITLE="answer competence across the ladder"
MODULE_WHY="answer competence across the ladder"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=(jacobian-lens/data/evaluations/lens-eval-association.json jacobian-lens/data/evaluations/lens-eval-multihop.json jacobian-lens/data/evaluations/lens-eval-multilingual.json jacobian-lens/data/evaluations/lens-eval-order-ops.json jacobian-lens/data/evaluations/lens-eval-poetry.json jacobian-lens/data/evaluations/lens-eval-typo.json)
OUTPUTS=(results/cv4_phase1_capability.json)
main() { run_py experiments/cv4_phase1_capability.py --models 70m,160m,410m,1b,1.4b,2.8b; }
module_main "$@"
