#!/usr/bin/env bash
# cv5_sensitivity — was rank blind where z is sighted?
#
# GENERATED by tools/emit_exp_modules.py from results/cv5_metric_sensitivity_410m.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="cv5_sensitivity"; MODULE_TITLE="was rank blind where z is sighted?"
MODULE_WHY="was rank blind where z is sighted?"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=(results/cv3_margins_410m.json results/e48/lens_INSTREAM_Pile-CC_410m_n200_s0.pt results/e66_fitter_equivalence_cuda.json)
OUTPUTS=(results/cv5_metric_sensitivity_410m.json)
main() { run_py experiments/cv5_metric_sensitivity.py; }
module_main "$@"
