#!/usr/bin/env bash
# cv6_ladder — does the per-family corpus effect replicate at 1.4B and 2.8B?
#
# GENERATED by tools/emit_exp_modules.py from results/cv6_per_family_ladder.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="cv6_ladder"; MODULE_TITLE="does the per-family corpus effect replicate at 1"
MODULE_WHY="does the per-family corpus effect replicate at 1.4B and 2.8B?"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=(results/cv6/cv6_1.4b_n25.json results/cv6/cv6_2.8b_n25.json results/cv6/cv6_c0_scorer_equivalence.json results/d3_corpus_by_family_410m.json)
OUTPUTS=(results/cv6_per_family_ladder.json)
main() { run_py experiments/cv6_per_family_ladder.py --adjudicate; }
module_main "$@"
