#!/usr/bin/env bash
# cv7_rung — the 1B rung of the per-family ladder
#
# GENERATED by tools/emit_exp_modules.py from results/cv7_1b_rung.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
#
# PATHS IN THE INVOCATION BELOW ARE REPO-RELATIVE. The raw record may hold an absolute path from
# the machine that ran it -- a home directory, or a rented GPU box's /workspace that no longer
# exists. Only paths were rewritten; every flag is byte-identical to `provenance.argv`.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="cv7_rung"; MODULE_TITLE="the 1B rung of the per-family ladder"
MODULE_WHY="the 1B rung of the per-family ladder"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=(results/cv6_per_family_ladder.json results/cv7/cv7_1b_n200.json results/d3_corpus_by_family_410m.json)
OUTPUTS=(results/cv7_1b_rung.json)
main() { run_py experiments/cv7_1b_rung.py --adjudicate; }
module_main "$@"
