#!/usr/bin/env bash
# d1_union — is min's preference for a derangement a union artifact?
#
# GENERATED by tools/emit_exp_modules.py from results/d1_min_union_diagnostic_410m.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="d1_union"; MODULE_TITLE="is min's preference for a derangement a union ar"
MODULE_WHY="is min's preference for a derangement a union artifact?"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=(results/lenses/e28/e28_Github_410m_n200_s0.pt results/lenses/e28/e28_Pile-CC_410m_n200_s0.pt results/lenses/e28/e28_USPTO_Backgrounds_410m_n200_s0.pt results/e48_crossover_410m.json)
OUTPUTS=(results/d1_min_union_diagnostic_410m.json)
main() { run_py experiments/d1_min_union_diagnostic.py --corpora USPTO_Backgrounds,Pile-CC,Github --n-derangements 3; }
module_main "$@"
