#!/usr/bin/env bash
# dn1_design_nulls — does the design null agree with the permutation null?
#
# GENERATED by tools/emit_exp_modules.py from results/dn1_design_nulls.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
#
# PATHS IN THE INVOCATION BELOW ARE REPO-RELATIVE. The raw record may hold an absolute path from
# the machine that ran it -- a home directory, or a rented GPU box's /workspace that no longer
# exists. Only paths were rewritten; every flag is byte-identical to `provenance.argv`.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="dn1_design_nulls"; MODULE_TITLE="does the design null agree with the permutation "
MODULE_WHY="does the design null agree with the permutation null?"
MODULE_COST="free (CPU)"
MODULE_TIER="T0"
INPUTS=(results/d3_corpus_by_family_410m.json results/r9_permutation_calibrated_min.json)
OUTPUTS=(results/dn1_design_nulls.json)
main() { run_py experiments/dn1_design_nulls.py; }
module_main "$@"
