#!/usr/bin/env bash
# e54_aggregation — the derangement audit at the corrected readout
#
# GENERATED by tools/emit_exp_modules.py from results/e54_aggregation_audit_rstrip_v2.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="e54_aggregation"; MODULE_TITLE="the derangement audit at the corrected readout"
MODULE_WHY="the derangement audit at the corrected readout"
MODULE_COST="free (recomputation over stored results)"
MODULE_TIER="T0"
INPUTS=(results/e33_logit_baseline_410m_v2.json results/e36_qladder_410m_rstrip.json results/e48_crossover_410m_rstrip.json results/e48c_exposure_vs_read.json results/e51_interaction_variance.json results/e52_factorial_410m_rstrip.json)
OUTPUTS=(results/e54_aggregation_audit_rstrip_v2.json)
main() { run_py experiments/t54_aggregation_audit.py --e52 results/e52_factorial_410m_rstrip.json --e36 results/e36_qladder_410m_rstrip.json --e48 results/e48_crossover_410m_rstrip.json --out results/e54_aggregation_audit_rstrip_v2.json; }
module_main "$@"
