#!/usr/bin/env bash
# e55_matrix — does the matching effect replicate on an independent operator population?
#
# GENERATED by tools/emit_exp_modules.py from results/e55_matrix_robustness_rstrip.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
#
# PATHS IN THE INVOCATION BELOW ARE REPO-RELATIVE. The raw record may hold an absolute path from
# the machine that ran it -- a home directory, or a rented GPU box's /workspace that no longer
# exists. Only paths were rewritten; every flag is byte-identical to `provenance.argv`.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="e55_matrix"; MODULE_TITLE="does the matching effect replicate on an indepen"
MODULE_WHY="does the matching effect replicate on an independent operator population?"
MODULE_COST="free (recomputation over stored results)"
MODULE_TIER="T0"
INPUTS=(results/e36_qladder_410m_rstrip.json results/e52_factorial_410m_rstrip.json results/e54_aggregation_audit.json)
OUTPUTS=(results/e55_matrix_robustness_rstrip.json)
main() { run_py experiments/t55_matrix_robustness.py --e52 results/e52_factorial_410m_rstrip.json --e36 results/e36_qladder_410m_rstrip.json --out results/e55_matrix_robustness_rstrip.json; }
module_main "$@"
