#!/usr/bin/env bash
# e57_variance_ci — an interval on the headline variance decomposition
#
# GENERATED by tools/emit_exp_modules.py from results/e57_grid_variance_ci_rstrip.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="e57_variance_ci"; MODULE_TITLE="an interval on the headline variance decompositi"
MODULE_WHY="an interval on the headline variance decomposition"
MODULE_COST="free (CPU)"
MODULE_TIER="T0"
INPUTS=(results/e52_factorial_410m.json results/e57_factorial_cells_410m_rstrip.json)
OUTPUTS=(results/e57_grid_variance_ci_rstrip.json)
main() { run_py experiments/t57_grid_variance_ci.py --cells results/e57_factorial_cells_410m_rstrip.json --e52 results/e52_factorial_410m_rstrip.json --out results/e57_grid_variance_ci_rstrip.json; }
module_main "$@"
