#!/usr/bin/env bash
# e58_algebra — algebra and measurement checks the validity audit left open
#
# GENERATED by tools/emit_exp_modules.py from results/e58_algebra_audit.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="e58_algebra"; MODULE_TITLE="algebra and measurement checks the validity audi"
MODULE_WHY="algebra and measurement checks the validity audit left open"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=(results/lenses/e28/e28_Github_410m_n400_s0.pt results/lenses/e28/e28_Pile-CC_410m_n400_s0.pt results/lenses/e28/e28_StackExchange_410m_n400_s0.pt results/lenses/e28/e28_USPTO_Backgrounds_410m_n400_s0.pt results/lenses/e28/e28_Wikipedia_en_410m_n400_s0.pt results/e45_disagreement_geometry.json)
OUTPUTS=(results/e58_algebra_audit.json)
main() { run_py experiments/t58_algebra_audit.py --device cpu; }
module_main "$@"
