#!/usr/bin/env bash
# e61_adjudicate — the randomised-network null, adjudicated
#
# GENERATED by tools/emit_exp_modules.py from results/e61_randomized_null_410m.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
#
# PATHS IN THE INVOCATION BELOW ARE REPO-RELATIVE. The raw record may hold an absolute path from
# the machine that ran it -- a home directory, or a rented GPU box's /workspace that no longer
# exists. Only paths were rewritten; every flag is byte-identical to `provenance.argv`.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="e61_adjudicate"; MODULE_TITLE="the randomised-network null, adjudicated"
MODULE_WHY="the randomised-network null, adjudicated"
MODULE_COST="free (CPU)"
MODULE_TIER="T0"
INPUTS=(results/e61/tv_rand_Github_s0.json results/e61/tv_rand_Github_s1.json results/e61/tv_rand_Github_s2.json results/e61/tv_rand_Pile-CC_s0.json results/e61/tv_rand_Pile-CC_s1.json results/e61/tv_rand_Pile-CC_s2.json)
OUTPUTS=(results/e61_randomized_null_410m.json)
main() { run_py experiments/t61_adjudicate_null.py; }
module_main "$@"
