#!/usr/bin/env bash
# e65_ckpt_geometry — trained small model, or undertrained?
#
# GENERATED by tools/emit_exp_modules.py from results/e65_ckpt_geometry_410m.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="e65_ckpt_geometry"; MODULE_TITLE="trained small model, or undertrained?"
MODULE_WHY="trained small model, or undertrained?"
MODULE_COST="free (CPU)"
MODULE_TIER="T1"
INPUTS=()
OUTPUTS=(results/e65_ckpt_geometry_410m.json)
main() { run_py experiments/t65_ckpt_geometry.py --model 410m; }
module_main "$@"
