#!/usr/bin/env bash
# e66c_post — WHY UNSTATED — add it to KNOWN
#
# GENERATED by tools/emit_exp_modules.py from results/e66c_post_provenance_repro.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
#
# PATHS IN THE INVOCATION BELOW ARE REPO-RELATIVE. The raw record may hold an absolute path from
# the machine that ran it -- a home directory, or a rented GPU box's /workspace that no longer
# exists. Only paths were rewritten; every flag is byte-identical to `provenance.argv`.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="e66c_post"; MODULE_TITLE="WHY UNSTATED — add it to KNOWN"
MODULE_WHY="WHY UNSTATED — add it to KNOWN"
MODULE_COST="GPU — price with ./lab cost before running"
MODULE_TIER="T2"
INPUTS=(corpora/Pile-CC.jsonl results/r6/lens_R6_Pile-CC_b0_410m_n200.pt)
OUTPUTS=(results/e66c_post_provenance_repro.json)
main() { run_py experiments/e66c_post_provenance_repro.py --dim-batch 32; }
module_main "$@"
