#!/usr/bin/env bash
# os1_operator_space — how far apart are the fitted operators?
#
# GENERATED by tools/emit_exp_modules.py from results/os1_operator_space_410m.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
#
# PATHS IN THE INVOCATION BELOW ARE REPO-RELATIVE. The raw record may hold an absolute path from
# the machine that ran it -- a home directory, or a rented GPU box's /workspace that no longer
# exists. Only paths were rewritten; every flag is byte-identical to `provenance.argv`.
# RETIERED 2026-08-31 T0 -> T1 by the generator's own rule (emit_exp_modules.py:290-292).
# experiments/os1_operator_space.py called write_result with no `inputs`, so provenance.inputs
# was empty, so `needs_pt` was False and this module was tagged T0 -- a tier that promises a
# reviewer it runs from the repo alone. It loads 32 .pt. The script now declares them; this
# module is out of the generator's paper-derived scope, so the rule was applied directly.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="os1_operator_space"; MODULE_TITLE="how far apart are the fitted operators?"
MODULE_WHY="how far apart are the fitted operators?"
MODULE_COST="free (CPU) — recomputes over 32 stored .pt operators, ~60 s"
MODULE_TIER="T1"
INPUTS=(results/e48/lens_INSTREAM_Wikipedia_en_410m_n200_s0.pt results/e48/lens_INSTREAM_Wikipedia_en_410m_n200_s1.pt results/e48/lens_INSTREAM_Wikipedia_en_410m_n200_s2.pt results/e48/lens_INSTREAM_USPTO_Backgrounds_410m_n200_s0.pt results/e48/lens_INSTREAM_USPTO_Backgrounds_410m_n200_s1.pt results/e48/lens_INSTREAM_USPTO_Backgrounds_410m_n200_s2.pt results/e48/lens_INSTREAM_Pile-CC_410m_n200_s0.pt results/e48/lens_INSTREAM_Pile-CC_410m_n200_s1.pt results/e48/lens_INSTREAM_Pile-CC_410m_n200_s2.pt results/e48/lens_INSTREAM_StackExchange_410m_n200_s0.pt results/e48/lens_INSTREAM_StackExchange_410m_n200_s1.pt results/e48/lens_INSTREAM_StackExchange_410m_n200_s2.pt results/e48/lens_INSTREAM_Github_410m_n200_s0.pt results/e48/lens_INSTREAM_Github_410m_n200_s1.pt results/e48/lens_INSTREAM_Github_410m_n200_s2.pt results/e48/lens_OOD_News_2024_410m_n200_s0.pt results/e48/lens_OOD_News_2024_410m_n200_s1.pt results/e48/lens_OOD_News_2024_410m_n200_s2.pt results/e48/lens_OOD_arXiv_2023_410m_n200_s0.pt results/e48/lens_OOD_arXiv_2023_410m_n200_s1.pt results/e48/lens_OOD_arXiv_2023_410m_n200_s2.pt results/e48/lens_OOD_CommonPile_410m_n200_s0.pt results/e48/lens_OOD_CommonPile_410m_n200_s1.pt results/e48/lens_OOD_CommonPile_410m_n200_s2.pt results/r6/lens_R6_Pile-CC_b0_410m_n200.pt results/r6/lens_R6_Pile-CC_b1_410m_n200.pt results/r6/lens_R6_Pile-CC_b2_410m_n200.pt results/r6/lens_R6_Pile-CC_b3_410m_n200.pt results/r6/lens_R6_Wikipedia_en_b0_410m_n200.pt results/r6/lens_R6_Wikipedia_en_b1_410m_n200.pt results/r6/lens_R6_Wikipedia_en_b2_410m_n200.pt results/r6/lens_R6_Wikipedia_en_b3_410m_n200.pt)
OUTPUTS=(results/os1_operator_space_410m.json)
main() { run_py experiments/os1_operator_space.py; }
module_main "$@"
