#!/usr/bin/env bash
# paper_clustered_t — the corpus-clustered t on the derangement gap
#
# GENERATED by tools/emit_exp_modules.py from results/paper_clustered_derangement_t.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="paper_clustered_t"; MODULE_TITLE="the corpus-clustered t on the derangement gap"
MODULE_WHY="the corpus-clustered t on the derangement gap"
MODULE_COST="free (recomputation over stored results)"
MODULE_TIER="T0"
INPUTS=(results/e54_aggregation_audit.json results/e54_aggregation_audit_rstrip_v2.json)
OUTPUTS=(results/paper_clustered_derangement_t.json)
main() { run_py tools/paper_clustered_derangement_t.py; }
module_main "$@"
