#!/usr/bin/env bash
# r5_corpus_axis — corpus-axis uncertainty, stated as such
#
# GENERATED by tools/emit_exp_modules.py from results/r5_corpus_axis_uncertainty_rstrip.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="r5_corpus_axis"; MODULE_TITLE="corpus-axis uncertainty, stated as such"
MODULE_WHY="corpus-axis uncertainty, stated as such"
MODULE_COST="free (recomputation over stored results)"
MODULE_TIER="T0"
INPUTS=(results/e57_factorial_cells_410m_rstrip.json results/e57_grid_variance_ci_rstrip.json)
OUTPUTS=(results/r5_corpus_axis_uncertainty_rstrip.json)
main() { run_py tools/r5_corpus_axis_uncertainty.py --cells results/e57_factorial_cells_410m_rstrip.json --ci results/e57_grid_variance_ci_rstrip.json; }
module_main "$@"
