#!/usr/bin/env bash
# r7_matched_pools — does the effect survive matching the pools on lexical composition?
#
# GENERATED by tools/emit_exp_modules.py from results/r7_matched_pools_410m.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
#
# PATHS IN THE INVOCATION BELOW ARE REPO-RELATIVE. The raw record may hold an absolute path from
# the machine that ran it -- a home directory, or a rented GPU box's /workspace that no longer
# exists. Only paths were rewritten; every flag is byte-identical to `provenance.argv`.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="r7_matched_pools"; MODULE_TITLE="does the effect survive matching the pools on le"
MODULE_WHY="does the effect survive matching the pools on lexical composition?"
MODULE_COST="GPU — price with ./lab cost before running"
MODULE_TIER="T2"
INPUTS=(corpora/Github.jsonl corpora/Pile-CC.jsonl corpora/StackExchange.jsonl corpora/USPTO_Backgrounds.jsonl corpora/Wikipedia_en.jsonl)
OUTPUTS=(results/r7_matched_pools_410m.json)
main() { run_py experiments/r7_matched_pools.py --device cuda --lens-dir results/r7 --out results/r7_matched_pools_410m.json; }
module_main "$@"
