#!/usr/bin/env bash
# r8_flatness — does S2 survive at the corrected readout?
#
# GENERATED by tools/emit_exp_modules.py from results/r8_ladder_flatness.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="r8_flatness"; MODULE_TITLE="does S2 survive at the corrected readout?"
MODULE_WHY="does S2 survive at the corrected readout?"
MODULE_COST="free (recomputation over stored results)"
MODULE_TIER="T0"
INPUTS=(results/ladder410_cpu_rstrip/ladder_Github_s0.json results/ladder410_cpu_rstrip/ladder_Github_s1.json results/ladder410_cpu_rstrip/ladder_Github_s2.json results/ladder410_cpu_rstrip/ladder_Pile-CC_s0.json results/ladder410_cpu_rstrip/ladder_Pile-CC_s1.json results/ladder410_cpu_rstrip/ladder_Pile-CC_s2.json)
OUTPUTS=(results/r8_ladder_flatness.json)
main() { run_py tools/r8_ladder_flatness.py; }
module_main "$@"
