#!/usr/bin/env bash
# r9_calibrated_min — the published statistic against its own null
#
# GENERATED by tools/emit_exp_modules.py from results/r9_permutation_calibrated_min.json. Do not hand-edit; regenerate.
# The invocation below is `provenance.argv` of that file: the command that actually produced the
# stored number, not a reconstruction. INPUTS are `provenance.inputs`.
#
# Regenerating will NOT reproduce the payload byte-for-byte where the script has changed since;
# `docs/reproducibility/SCRIPT_PROVENANCE.md` names the exact code each result was produced by, and
# `repro/scripts_at_run/` carries it.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"
MODULE_ID="r9_calibrated_min"; MODULE_TITLE="the published statistic against its own null"
MODULE_WHY="the published statistic against its own null"
MODULE_COST="free (recomputation over stored results)"
MODULE_TIER="T0"
INPUTS=(results/e48_crossover_410m_rstrip.json)
OUTPUTS=(results/r9_permutation_calibrated_min.json)
main() { run_py tools/r9_permutation_calibrated_min.py; }
module_main "$@"
