#!/usr/bin/env bash
# repro/06_data.sh — THE DATA MODULE. Where every corpus came from, pinned; and the provenance
# chain from Pythia's own repository down to a measured containment number.
#
#   bash repro/06_data.sh                # provenance + verify. Read-only, downloads no corpora
#   bash repro/06_data.sh --provenance   # the chain only: clone Pythia, check shapes, check pins
#   bash repro/06_data.sh --build        # build the pool AT THE PINNED REVISIONS, then verify
#   bash repro/06_data.sh --verify       # hash-verify a pool already on disk
#   bash repro/06_data.sh --pile         # build the five Pile components only
#   bash repro/06_data.sh --ood          # build the OOD / TRAP / CONTROL panel only
#
# WHY THIS EXISTS, AND WHY THE POOL IS NOT SHIPPED
#   The artifact mirror is CC BY 4.0. That licence can only cover what this work owns: the fitted
#   operators and the results records. The corpus plaintext is third-party text under upstream
#   terms, and two of the eleven files are Wikipedia-derived and carry CC BY-SA, which is
#   SHARE-ALIKE and cannot be relicensed as CC BY 4.0. Rather than ship a mixed-licence mirror,
#   the pool is not distributed at all. This script rebuilds it from the same public sources.
#
#   What IS shipped is corpora/manifest.json and corpora/manifest_ood.json — this work's own
#   record of the pool: per-file SHA-256, document counts, the exact HF dataset id and config,
#   and the disjoint seed-block ranges. Those are facts about the build, they are ours, and they
#   are what makes the rebuild checkable rather than merely repeatable.
#
# MEASURED 2026-08-31, on this machine, against the shipped manifests:
#   Pile-CC, StackExchange, Wikipedia_en, Github, USPTO_Backgrounds   5/5 BIT-IDENTICAL
#   OOD_CommonPile, TRAP_FineWeb, CONTROL_PubMed_2023                 3/3 BIT-IDENTICAL
#   manifest.json itself regenerated BYTE-IDENTICALLY.
#   OOD_Wikipedia_2023 and OOD_arXiv_2023 were NOT re-run (53 MB and 110 MB of streaming);
#   they carry SHA-256 in the manifest, so this script checks them if you build them.
#
# REVISION PINNING (2026-09-01). Until then both builders called load_dataset() with NO
# `revision=`, so the pool depended on whatever upstream was that day, and
# the release procedure finding B0 concluded the pool "is not regenerable". The rebuild
# above showed it regenerating bit-identically — evidence upstream had not moved, not a guarantee.
# corpora/dataset_revisions.json now pins the dataset commit for all eight upstreams, both
# builders read it, and pinned_load() REFUSES to load anything unpinned. B0 is closed.
#
# NOTE ON SYNTAX. load_dataset()'s second positional is the CONFIG name, not a locale.
# monology/pile-uncopyrighted declares NO configs, so none may be passed; wikimedia/wikipedia
# (20231101.en), RealTimeData/bbc_news_alltime (2024-06) and HuggingFaceFW/fineweb (sample-10BT)
# each take one, and those three are the reason the OOD panel is stable by construction.

# EleutherAI/pythia, pinned. The provenance section clones this and reads its README.
PYTHIA_PIN="a19eecb807ec2c79a39ebf18108816e6ffffc1d5"

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
need_py
cd "$REPO_ROOT"

provenance() {
  hdr "1. Pythia's own repository — what it says it was trained on"
  local D="${TMPDIR:-/tmp}/pythia_provenance"
  if [ -d "$D/.git" ]; then
    git -C "$D" fetch --quiet --depth 1 origin "$PYTHIA_PIN" 2>/dev/null || true
    git -C "$D" checkout --quiet "$PYTHIA_PIN" 2>/dev/null || true
  else
    rm -rf "$D"
    git clone --quiet https://github.com/EleutherAI/pythia "$D" || die "cannot clone EleutherAI/pythia"
    git -C "$D" checkout --quiet "$PYTHIA_PIN" || warn "could not pin; using default branch"
  fi
  local got; got="$(git -C "$D" rev-parse HEAD)"
  info "EleutherAI/pythia @ ${got:0:12}"
  [ "$got" = "$PYTHIA_PIN" ] && ok "pinned at ${PYTHIA_PIN:0:12}" \
                             || warn "HEAD is ${got:0:12}, expected ${PYTHIA_PIN:0:12}"

  grep -q "trained on the exact same data, in the exact same order" "$D/README.md" \
    && ok "README: all sizes trained on the SAME data in the SAME order" \
    || bad "README no longer states the same-data-same-order property"
  grep -qi "deduplication applied" "$D/README.md" \
    && ok "README: a deduplicated Pile variant exists (we use the -deduped models)" \
    || bad "README no longer describes the deduped variant"
  grep -q "299,892,736,000" "$D/README.md" \
    && ok "README: 299,892,736,000 (~300B) tokens seen per model" \
    || warn "the token count in README has changed"
  grep -q "EleutherAI/pile-deduped-pythia-preshuffled" "$D/README.md" \
    && ok "README names EleutherAI/pile-deduped-pythia-preshuffled as the deduped stream" \
    || bad "README no longer names the preshuffled deduped stream"
  [ -f "$D/utils/20B_tokenizer.json" ] \
    && ok "utils/20B_tokenizer.json present — containment gate G1's reference tokenizer" \
    || bad "the 20B tokenizer is absent; containment gate G1 cannot be checked"

  hdr "2. Our model shapes against Pythia's own table"
  "$PY" - "$D/README.md" <<'PYEOF'
import re, sys
rows = [l for l in open(sys.argv[1]) if re.match(r'^\|\s*(70M|160M|410M|1B|1\.4B|2\.8B|6\.9B|12B)\s*\|', l)]
# these are repro/lib/common.sh's model_shape(), which prices every GPU run
ours = {"70m": (6, 512), "160m": (12, 768), "410m": (24, 1024), "1b": (16, 2048),
        "1.4b": (24, 2048), "2.8b": (32, 2560), "6.9b": (32, 4096), "12b": (36, 5120)}
ok = bad = 0
for l in rows:
    c = [x.strip() for x in l.strip().strip('|').split('|')]
    L, D = int(c[1]), int(c[2])
    same = ours.get(c[0].lower()) == (L, D)
    ok, bad = (ok + 1, bad) if same else (ok, bad + 1)
    print(f"     {c[0]:6s} pythia=({L:2d},{D:5d})  ours={ours.get(c[0].lower())}  "
          f"{'match' if same else 'MISMATCH'}")
print(f"     {ok} match, {bad} mismatch")
raise SystemExit(1 if bad else 0)
PYEOF
  [ $? -eq 0 ] && ok "every model shape matches Pythia's published table" \
               || bad "a model shape disagrees with Pythia — repro/lib/common.sh prices runs from these"

  hdr "3. The pinned dataset revisions still resolve on the Hub"
  "$PY" - <<'PYEOF'
import json, os
from huggingface_hub import HfApi
api = HfApi()
revs = {k: v for k, v in json.load(open("corpora/dataset_revisions.json")).items()
        if not k.startswith("_")}
bad = 0
for name, d in revs.items():
    try:
        live = api.dataset_info(name).sha
    except Exception as e:
        print(f"     {name:46s} UNREACHABLE ({type(e).__name__})"); bad += 1; continue
    pin = d["sha"]
    if live == pin:
        print(f"     {name:46s} {pin[:12]}  pin == current HEAD")
    else:
        # NOT an error. The pin is what we built from; upstream moving is expected and is
        # exactly why the pin exists. What would be an error is having no pin at all.
        print(f"     {name:46s} {pin[:12]}  pin held; upstream HEAD is now {live[:12]}")
print(f"     {len(revs) - bad} of {len(revs)} pinned datasets resolve")
raise SystemExit(1 if bad else 0)
PYEOF
  [ $? -eq 0 ] && ok "every pinned dataset resolves" || bad "a pinned dataset is unreachable"

  hdr "4. The empirical link — measured containment against the real stream"
  info "Documentation says what Pythia was trained on. E35/M1 MEASURED it: it streams"
  info "EleutherAI/pile-deduped-pythia-preshuffled and computes n-gram containment for"
  info "each corpus. That is the evidence the OOD panel is outside the training stream."
  "$PY" - <<'PYEOF'
import json, os
p = "results/m1/m1_5shard.json"
if not os.path.exists(p):
    print("     results/m1/m1_5shard.json absent — fetch results first"); raise SystemExit(0)
d = json.load(open(p))
k = str(d.get("k_selected", 32))
c = (d.get("containment") or {}).get(k, {})
print(f"     containment at k={k} (fraction of each corpus's k-grams found in the stream):")
for q, v in sorted(c.items(), key=lambda kv: -kv[1]["containment"]):
    print(f"       {q:24s} {v['containment']:.5f}   ({v['n_found']:,} of {v['n_distinct_kgrams']:,})")
ctl = (d.get("controls") or {}).get("M1_C2_random_containment", {})
if ctl:
    print(f"     CONTROL random-token containment: {ctl.get(k)}  "
          f"(fires: {(d.get('controls') or {}).get('M1_C2_fires')})")
    print("       A control that cannot fail is not a control. Random tokens must score 0.")
PYEOF
  ok "provenance chain demonstrated"
}

MODE="${1:-}"
DO_PILE=1; DO_OOD=1; VERIFY_ONLY=0; DO_PROV=0; DO_BUILD=0
case "$MODE" in
  --provenance) DO_PROV=1; VERIFY_ONLY=1; DO_PILE=0; DO_OOD=0 ;;
  --build)      DO_BUILD=1 ;;
  --verify)     VERIFY_ONLY=1 ;;
  --pile)       DO_BUILD=1; DO_OOD=0 ;;
  --ood)        DO_BUILD=1; DO_PILE=0 ;;
  "")           DO_PROV=1; VERIFY_ONLY=1 ;;
  *) die "unknown argument '$MODE' — use --provenance, --build, --verify, --pile, --ood" ;;
esac

[ "$DO_PROV" -eq 1 ] && provenance

if [ "$DO_BUILD" -eq 1 ]; then
  [ "$DO_PILE" -eq 1 ] && { hdr "Building the five Pile components"; \
    info "streams monology/pile-uncopyrighted; ~40k rows, a few minutes"; \
    "$PY" src/build_corpora.py || die "build_corpora.py failed"; }
  [ "$DO_OOD" -eq 1 ] && { hdr "Building the OOD / TRAP / CONTROL panel"; \
    info "skips anything already present with the right document count"; \
    "$PY" src/build_ood_corpora.py || die "build_ood_corpora.py failed"; }
fi

hdr "Verify every built file against its shipped manifest"
"$PY" - <<'PYEOF'
import hashlib, json, os, sys

ok = bad = absent = 0
rows = []
for man_path in ("corpora/manifest.json", "corpora/manifest_ood.json"):
    if not os.path.exists(man_path):
        print(f"  ! {man_path} is missing — it ships with the repository; nothing to verify against")
        continue
    for name, d in json.load(open(man_path)).items():
        if not isinstance(d, dict) or "sha256" not in d:
            continue
        p = os.path.join("corpora", d["file"])
        if not os.path.isfile(p):
            rows.append((name, "NOT BUILT", "")); absent += 1; continue
        h = hashlib.sha256(open(p, "rb").read()).hexdigest()
        if h == d["sha256"]:
            rows.append((name, "BIT-IDENTICAL", "")); ok += 1
        else:
            rows.append((name, "DIFFERS", f"manifest {d['sha256'][:12]} != rebuilt {h[:12]}"))
            bad += 1

w = max((len(r[0]) for r in rows), default=10)
for n, v, why in rows:
    print(f"  {n:<{w}}  {v:<14} {why}")
print(f"\n  {ok} bit-identical, {bad} differ, {absent} not built")
if bad:
    print("\n  A DIFFERENCE IS A FINDING, NOT A CRASH. The manifest records the pool this work\n"
          "  actually used. If a rebuild no longer matches it, the upstream dataset moved since\n"
          "  2026-08-31. Report the mismatch; do not silently proceed with a different pool.")
raise SystemExit(1 if bad else 0)
PYEOF
rc=$?

hdr "Next"
if [ "$rc" -eq 0 ]; then
  ok "the pool matches the manifest"
  echo "  bash repro/RUN_ALL.sh --tier T1     re-score the stored operators"
else
  bad "the rebuilt pool does not match the manifest — read the note above before continuing"
fi
exit $rc
