#!/usr/bin/env python3
"""build_taxonomy.py — emit the appendix of RESULTS_TAXONOMY.md from the results tree itself.

WHY THIS IS GENERATED RATHER THAN WRITTEN
  A hand-maintained inventory of "what we can reproduce" goes stale the first time anyone runs
  anything, and this programme has already lost a week to a headline number that lived only in
  prose. The CLAIMS in RESULTS_TAXONOMY.md are authored — a claim is a judgement and cannot be
  extracted from JSON — but the PROVENANCE half is generated here, so the two cannot drift:
  if a results file loses its stamp, or its script changes, the next run of this script says so.

WHAT IT EMITS
  One row per results file: the experiment, the script that wrote it, the commit, whether the
  script has changed since, whether the stored payload hash still matches, and how many inputs
  were hashed. Files with no provenance block are listed separately and counted, because that
  count is the honest measure of how much of the tree is auditable.

    python tools/build_taxonomy.py                 # print
    python tools/build_taxonomy.py --out FILE.md   # write the appendix fragment
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PY = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(PY, "src"))
from provenance import verify_result  # noqa: E402

# families whose members are bulk artifacts, not standalone results: rolled up, not listed
BULK = ("e28_", "ladder410/", "ladder1b/", "tv_", "lens_")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    files = sorted(glob.glob(os.path.join(PY, "results", "*.json"))
                   + glob.glob(os.path.join(PY, "results", "*", "*.json")))
    stamped, bare, bulk = [], [], {}
    for f in files:
        rel = os.path.relpath(f, PY)
        base = os.path.basename(f)
        if "_provenance" in base or "smoke" in base:
            continue
        if any(k in rel for k in BULK):
            fam = rel.split("/")[1] if "/" in rel[len("results/"):] else base.split("_")[0]
            bulk[fam] = bulk.get(fam, 0) + 1
            continue
        try:
            d = json.load(open(f))
        except Exception:
            continue
        if not isinstance(d, dict):
            continue
        if d.get("provenance"):
            v = verify_result(f)
            stamped.append((rel, d, v))
        else:
            bare.append((rel, d))

    L = []
    L.append("## Appendix A — provenance status of every results file\n")
    L.append(f"*Generated by `tools/build_taxonomy.py`. "
             f"{len(stamped)} stamped, {len(bare)} unstamped, "
             f"{sum(bulk.values())} bulk artifacts rolled up.*\n")
    L.append("### A.1 Provenance-stamped — script, commit and inputs all recorded\n")
    L.append("| results file | experiment | script | commit | script unchanged | payload intact | inputs hashed |")
    L.append("|---|---|---|---|---|---|---|")
    for rel, d, v in stamped:
        p = d["provenance"]
        L.append(f"| `{os.path.basename(rel)}` | {p.get('experiment','—')} | "
                 f"`{os.path.basename(p['script']['path'])}` | `{p['git']['commit_short']}`"
                 f"{' *(dirty)*' if p['git']['dirty'] else ''} | "
                 f"{'yes' if v['script_unchanged'] else '**NO**'} | "
                 f"{'yes' if v['payload_sha_matches'] else '**NO**'} | {v['inputs_checked']} |")

    L.append("\n### A.2 No provenance block — recomputable, but not self-describing\n")
    L.append("These predate `provenance.py`. The script that produced each is known from the "
             "experiment number and its docstring, but the file does not record it, so a reader "
             "cannot verify the link without the repo's history.\n")
    L.append("| results file | experiment field | has verdict |")
    L.append("|---|---|---|")
    for rel, d in bare:
        exp = str(d.get("experiment", "—"))[:64]
        L.append(f"| `{os.path.basename(rel)}` | {exp} | "
                 f"{'yes' if ('VERDICT' in d or 'verdict' in d) else 'no'} |")

    L.append("\n### A.3 Bulk artifact families (rolled up)\n")
    for fam, n in sorted(bulk.items(), key=lambda kv: -kv[1]):
        L.append(f"- `{fam}` — {n} files")

    out = "\n".join(L) + "\n"
    if a.out:
        open(a.out, "w").write(out)
        print(f"wrote {a.out}  ({len(stamped)} stamped / {len(bare)} unstamped)")
    else:
        print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
