#!/usr/bin/env python3
"""
make_cv6_description.py — emit docs/experiments/descriptions/CV6.md from the results files.

WHY A GENERATOR. `docs/experiments/descriptions/` is built on ZERO ANALYSIS and on the rule that
**no number appears there that is not in a results file**. CV6's description carries ~70 numbers
across two models x five families x five corpora. Hand-transcribing them is exactly the operation
that produced the stale-transcription defects this programme keeps finding, so the document is
generated: every value below is read from the JSON and every table cell names the key it came from.

The generator writes facts about the record only — what ran, under what configuration, the
pre-registered rule verbatim, what each control produced against its stated bar, the numbers, and
the stored VERDICT string in quotes. It draws no conclusion. Interpretation belongs in
`docs/context/CONTEXT.md` and `docs/validity/DIAGNOSIS.md`, not here.

  .venv/bin/python tools/make_cv6_description.py
"""
import json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MAIN = os.path.join(ROOT, "results", "cv6_per_family_ladder.json")
C0 = os.path.join(ROOT, "results", "cv6", "cv6_c0_scorer_equivalence.json")
DEST = os.path.join(ROOT, "docs", "experiments", "descriptions", "CV6.md")
FAMS = ["multihop", "multilingual", "order-ops", "poetry", "typo"]
CORP = ["Wikipedia_en", "USPTO_Backgrounds", "Pile-CC", "StackExchange", "Github"]


def f(x, n=4):
    return "UNSTORED" if x is None else f"{x:.{n}f}"


def main():
    if not os.path.exists(MAIN):
        raise SystemExit(f"ABORT: {os.path.relpath(MAIN, ROOT)} does not exist — run "
                         f"`experiments/cv6_per_family_ladder.py --adjudicate` first")
    d = json.load(open(MAIN))
    c0 = json.load(open(C0)) if os.path.exists(C0) else None
    per = {s: json.load(open(os.path.join(ROOT, "results", "cv6", f"cv6_{s}_n{d['N']}.json")))
           for s in ("1.4b", "2.8b")}
    prov = d.get("provenance", {})
    o = []
    w = o.append

    w("# CV6 -- does the per-family corpus effect replicate at 1.4B and 2.8B?\n")
    w("**GENERATED by `tools/make_cv6_description.py`; do not edit by hand.** Every number is read "
      "from a results file and the key it came from is named. ZERO ANALYSIS, per "
      "[`../HOW_TO_READ_THIS.md`](../HOW_TO_READ_THIS.md): this document records what was run and "
      "what came out, never what it means.\n")

    w("## WHAT WAS RUN\n")
    npf = per["2.8b"]["n_pairs_per_family"]
    npf_str = ", ".join(f"{k} {v}" for k, v in npf.items())
    w(f"For each of `pythia-1.4b-deduped` and `pythia-2.8b-deduped`: the eval battery's activations "
      f"`h_t` were cached once on the fitting device at the fitting dtype, at each item's own readout "
      f"position on the **stripped** prompt, over the five admitted eval sets -- "
      f"{sum(npf.values())} scorable (item, intermediate) pairs in all ({npf_str}). "
      f"Then **15 operators** were fitted -- five in-stream "
      f"corpora x three disjoint seed blocks, N={d['N']} prompts each -- and every operator was "
      f"scored against that one cache, together with the unfitted identity (`logit_I`) arm. Each "
      f"operator was additionally re-scored through an fp16 round-trip, recorded as a diagnostic. "
      f"No number here is pooled across families.\n")

    w("## CONFIGURATION\n")
    w("| field | 1.4b | 2.8b | key |")
    w("|---|---|---|---|")
    rows = [
        ("model", "model"), ("n_layers", "n_layers"), ("band", "band"),
        ("N", "N"), ("device", "device"), ("dtype", "dtype"), ("gpu", "gpu"),
    ]
    for label, key in rows:
        w(f"| {label} | `{d['by_model']['1.4b'].get(key)}` | `{d['by_model']['2.8b'].get(key)}` "
          f"| `by_model.<m>.{key}` |")
    for label, key in (("dim_batch", "dim_batch"), ("max_seq_len", "max_seq_len"),
                       ("skip_first", "skip_first"), ("target_layer_arg", "target_layer_arg"),
                       ("target_layer_effective", "target_layer_effective"),
                       ("peak VRAM (GiB)", "peak_vram_gb"), ("torch", "torch"),
                       ("git commit at launch", "git_commit_at_launch")):
        w(f"| {label} | `{per['1.4b'].get(key)}` | `{per['2.8b'].get(key)}` "
          f"| `cv6_<m>_n{d['N']}.json -> {key}` |")
    # Shared rows: identical for both models by construction, so the value spans the two columns
    # as "same for both" rather than being duplicated or -- as a first draft did -- emitted with a
    # LaTeX \multicolumn, which is not markdown and rendered as a broken row.
    for label, val, key in (
            ("fitting corpora", ", ".join(d["corpora"]), "corpora"),
            ("seed blocks", str(d["seeds"]), "seeds"),
            ("eval sets", ", ".join(d["admitted_sets"]), "admitted_sets"),
            ("k-grid", str(d["K"]), "K"),
            ("readout", d["readout_convention"], "readout_convention"),
            ("pooling", d["pooling_convention"], "pooling_convention"),
            ("TF32", str(per["2.8b"].get("tf32")), f"cv6_<m>_n{d['N']}.json -> tf32")):
        w(f"| {label} | `{val}` | *(same)* | `{key}` |")
    w("")

    w("## PRE-REGISTERED RULE (verbatim)\n")
    w("From `docs/experiments/preregs/CV6_per_family_ladder.md`, stored in the results file at "
      "`decision_rule_verbatim`:\n")
    w("> " + d["decision_rule_verbatim"].replace(". ", ".\n> ") + "\n")
    w("PRIMARY, stored at `PRIMARY`: `R(f, m) = spread_z(f, m) / pooled_seed_sd_z(f, m)`, the spread "
      "taken across the five corpora and the seed SD the RMS of the per-corpus 3-seed sample SDs, "
      "**computed within that family**.\n")

    w("## CONTROLS (as recorded)\n")
    w("| control | required | observed | fired |")
    w("|---|---|---|---|")
    ctl = d["controls"]
    if c0:
        w(f"| C0 scorer equivalence | {c0['required']} | worst\\|dz\\| `{c0['worst_abs_dz']:.3e}`, "
          f"worst\\|drank\\| `{c0['worst_abs_drank']:.3e}`; negative control max\\|dz\\| "
          f"`{c0['negative_control']['max_abs_dz']:.3e}` | **{c0['fires']}** |")
    w(f"| C1 identity arm | {ctl['C1_logit_identity_arm']['required']} | emitted per model for all "
      f"five families; 1.4b pooled `{f(d['by_model']['1.4b']['logit_I_pooled_rank_flatmean7'], 11)}`, "
      f"2.8b pooled `{f(d['by_model']['2.8b']['logit_I_pooled_rank_flatmean7'], 11)}` "
      f"| **{ctl['C1_logit_identity_arm']['fires']}** |")
    c2 = ctl["C2_band_matches_rule"]["per_model"]
    w(f"| C2 band matches rule | {ctl['C2_band_matches_rule']['required']} | "
      f"1.4b `{c2['1.4b']['band'][0]}..{c2['1.4b']['band'][-1]}` == rule, "
      f"2.8b `{c2['2.8b']['band'][0]}..{c2['2.8b']['band'][-1]}` == rule "
      f"| **{ctl['C2_band_matches_rule']['fires']}** |")
    c3 = ctl["C3_seed_sd_nondegenerate"]
    w(f"| C3 seed SD non-degenerate | {c3['required']} | min over (family, model) = "
      f"`{min(min(v.values()) for v in c3['per_model'].values()):.3e}`; void cells "
      f"`{c3['void_cells'] or 'none'}` | **{c3['fires']}** |")
    c4 = ctl["C4_N_identical"]
    w(f"| C4 N identical | {c4['required']} | n_prompts seen `{c4['n_prompts_seen']}`, arms "
      f"`{c4['n_arms']}`, prompt SHAs identical across models on "
      f"`{sum(1 for v in c4['prompt_sha_identical_across_models'].values() if v)}/15` arms "
      f"| **{c4['fires']}** |")
    c5 = ctl["C5_device_precision"]
    w(f"| C5 device/precision | {c5['required']} | "
      + "; ".join(f"{m} `{v['device']}`/`{v['dtype']}` on `{v['gpu']}`"
                  for m, v in c5["per_model"].items())
      + f" | **{c5['fires']}** |")
    w("")

    w("## NUMBERS (as stored)\n")
    w("### PRIMARY -- R(f, 2.8B), the quantity the decision rule reads\n")
    w("| family | pairs | z spread | z pooled seed SD | **R** | Kendall tau vs 410M | "
      "R >= 10 | R < 5 | tau >= 0.6 |")
    w("|---|---:|---:|---:|---:|---:|:--:|:--:|:--:|")
    b28 = d["by_model"]["2.8b"]["by_family"]
    for fam in FAMS:
        x = b28[fam]
        R, tau = x["R"], x["kendall_tau_vs_410m"]
        w(f"| {fam} | {x['n_pairs']} | {f(x['z_spread'])} | {f(x['z_pooled_seed_sd'], 6)} | "
          f"**{f(R, 2)}** | {f(tau, 2)} | {'Y' if R is not None and R >= 10 else 'n'} | "
          f"{'Y' if R is not None and R < 5 else 'n'} | {'Y' if tau is not None and tau >= 0.6 else 'n'} |")
    p = d["PRIMARY"]
    w(f"\nCounts as stored at `PRIMARY`: `n_families_R_ge_10` = **{p['n_families_R_ge_10']}/5**, "
      f"`n_families_R_lt_5` = **{p['n_families_R_lt_5']}/5**, "
      f"`n_families_tau_ge_0.6` = **{p['n_families_tau_ge_0.6']}/5**.\n")

    for short in ("1.4b", "2.8b"):
        bm = d["by_model"][short]
        w(f"### {short} -- per family (`by_model.{short}.by_family`)\n")
        w("| family | pairs | logit_I z | z spread | z seed SD | R | tau vs 410M | "
          "rank spread/SD | best -> worst (z) |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---|")
        for fam in FAMS:
            x = bm["by_family"][fam]
            w(f"| {fam} | {x['n_pairs']} | {f(bm['logit_I'][fam]['z'], 3)} | {f(x['z_spread'])} | "
              f"{f(x['z_pooled_seed_sd'], 6)} | {f(x['R'], 2)} | {f(x['kendall_tau_vs_410m'], 2)} | "
              f"{f(x['rank_spread_over_sd'], 2)} | " + " > ".join(x["order_by_z"]) + " |")
        w("")
        w(f"#### {short} -- per corpus mean z, by family (`...by_family.<f>.per_corpus.<c>.z_mean`)\n")
        w("| family | " + " | ".join(CORP) + " |")
        w("|---|" + "---:|" * len(CORP))
        for fam in FAMS:
            pc = bm["by_family"][fam]["per_corpus"]
            w(f"| {fam} | " + " | ".join(f(pc[c]["z_mean"], 4) for c in CORP) + " |")
        w("")

    w("### 410M reference (`reference_410m`, from `results/d3_corpus_by_family_410m.json`, "
      "EXPLORATORY, N=200)\n")
    w("| family | R at 410M | best -> worst (z) at 410M |")
    w("|---|---:|---|")
    for fam in FAMS:
        w(f"| {fam} | {f(d['reference_410m']['R'][fam], 2)} | "
          + " > ".join(d["reference_410m"]["order_by_z"][fam]) + " |")
    w("")

    w("### fp16 round-trip diagnostic (`...by_family.<f>.fp16_roundtrip_diagnostic`)\n")
    w("Recorded because the 410M operators in `results/e48/` are STORED at fp16, so D3 scored an "
      "fp16-rounded operator while CV6's primary scores the fp32 accumulator. **Not a decision "
      "input.**\n")
    w("| model | family | R (fp32) | R (fp16 round-trip) | max abs d(z_mean) | ordering unchanged |")
    w("|---|---|---:|---:|---:|:--:|")
    for short in ("1.4b", "2.8b"):
        for fam in FAMS:
            x = d["by_model"][short]["by_family"][fam]
            g = x.get("fp16_roundtrip_diagnostic")
            if not g:
                continue
            w(f"| {short} | {fam} | {f(x['R'], 2)} | {f(g['R'], 2)} | {g['max_abs_dz_mean']:.3e} | "
              f"{g['order_unchanged']} |")
    w("")

    w("## VERDICT STRING AS STORED\n")
    w(f"`VERDICT` = **\"{d['VERDICT']}\"**\n")
    w(f"`verdict_note` = \"{d['verdict_note']}\"\n")

    w("## DECLARED BIAS AS STORED (`declared_bias`)\n")
    for b in d["declared_bias"]:
        w(f"* {b}")
    w("")

    w("## PROVENANCE\n")
    w("| field | value |")
    w("|---|---|")
    w(f"| results file | `results/cv6_per_family_ladder.json` |")
    w(f"| payload sha256 | `{prov.get('payload_sha256', 'UNSTORED')}` |")
    w(f"| script | `{prov.get('script', {}).get('path')}` sha256 "
      f"`{prov.get('script', {}).get('sha256')}` |")
    w(f"| git commit | `{prov.get('git', {}).get('commit_short')}` "
      f"dirty=`{prov.get('git', {}).get('dirty')}` |")
    w(f"| utc | `{prov.get('utc')}` |")
    w(f"| argv | `{' '.join(prov.get('argv', []))}` |")
    for short in ("1.4b", "2.8b"):
        pp = per[short].get("provenance", {})
        w(f"| per-model `cv6_{short}_n{d['N']}.json` | payload sha256 "
          f"`{pp.get('payload_sha256', 'UNSTORED')}`, utc `{pp.get('utc')}` |")
    if c0:
        cp = c0.get("provenance", {})
        w(f"| control `cv6/cv6_c0_scorer_equivalence.json` | payload sha256 "
          f"`{cp.get('payload_sha256', 'UNSTORED')}`, utc `{cp.get('utc')}` |")
    w("")
    w("## RELATED / SUPERSEDED FILES\n")
    w("| file | relation |")
    w("|---|---|")
    w("| `docs/experiments/preregs/CV6_per_family_ladder.md` | the pre-registration, committed "
      "before the code, with a visible post-registration AMENDMENT block |")
    w("| `results/d3_corpus_by_family_410m.json` | the 410M reference. EXPLORATORY -- no "
      "pre-registration, no decision rule. CV6's per-family estimand is disclosed as informed by it |")
    w("| `results/cv3_margins_410m.json` | established the corpus effect as a score effect at 410M "
      "and fixed z-space as the reporting choice |")
    w("| `results/cv4_phase1_capability.json` | CV4 Phase 1; Phases 2-3 are superseded by CV6 |")
    w("| `results/cv6/ht_cache_<m>.pt` | the cached `h_t`, so a re-score needs no forward passes |")
    w("| `results/cv6/lenses/lens_INSTREAM_<corpus>_<m>_n25_s<seed>.pt` | the 30 fitted operators, "
      "stored fp16 as the e48 convention does |")
    w("")

    os.makedirs(os.path.dirname(DEST), exist_ok=True)
    open(DEST, "w").write("\n".join(o))
    print(f"wrote {os.path.relpath(DEST, ROOT)} ({len(o)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
